packer {
  required_plugins {
    proxmox = {
      version = "~> 1"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

source "proxmox-iso" "ubuntu_2404" {
  proxmox_url              = "https://proxmox.empal.me:8006/api2/json"
  username                 = "root@pam!packer"
  token                    = "b256e5fa-a7c1-49eb-a085-9411cceddc5f"
  node                     = "proxmox"
  iso_file                 = "local:iso/ubuntu-24.04-live-server-amd64.iso"
  iso_storage_pool         = "local"
  unmount_iso              = true
  insecure_skip_tls_verify = true

  vm_name    = "ubuntu-24.04-template"
  vm_id      = 9000
  cores      = 2
  memory     = 2048
  os         = "l26"
  network_adapters {
    model  = "virtio"
    bridge = "vmbr0"
  }
  disks {
    type         = "scsi"
    disk_size    = "20G"
    storage_pool = "local-lvm"
  }
  
  # VM Cloud-Init Settings
  # cloud_init = true
  # cloud_init_storage_pool = "local-lvm"

  ssh_username         = "ubuntu"
  # (Option 1) Add your Password here
  # ssh_password = "ubuntu"
  # - or -
  # (Option 2) Add your Private SSH KEY file here
  ssh_private_key_file = "~/.ssh/id_ed25519"
  ssh_timeout          = "30m"
  ssh_handshake_attempts = 20

  template_name        = "ubuntu-24.04-template"
  template_description = "Ubuntu 24.04 LTS Live Server template, generated by Packer"

  boot_command = [
      "<esc><wait>",
      "e<wait>",
      "<down><down><down><end>",
      "<bs><bs><bs><bs><wait>",
      "autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---<wait>",
      "<f10><wait>"
  ]
  boot_wait = "5s"

  http_directory = "http"
}

build {
  sources = ["source.proxmox-iso.ubuntu_2404"]

  provisioner "shell" {
    pause_before = "60s"
    inline = [
      "sudo apt-get update",
      "sudo apt-get upgrade -y"
    ]
  }
}